#lang racket/base

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incorrect-password amount)
    "Incorrect password")
  (define (dispatch try-password m)
    (cond ((not (eq? try-password password)) incorrect-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

(define (make-joint account account-password password)
  (define (incorrect-password x)
    "Incorrect password")
  (define (dispatch try-password m)
    (cond ((not (eq? try-password password)) incorrect-password)
          (else (account account-password m))))
  dispatch)

(provide (all-defined-out))
